<?php
require_once('/var/projects/Luki/Cache/memoryAdapter.php');

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-24 at 14:10:35.
 */
class Luki_Cache_memoryAdapterTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Luki_Cache_memoryAdapter
	 */
	protected $object;
	
	protected $key = 'savedKey';
	
	protected $value = '1234567890';

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Luki_Cache_memoryAdapter;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}

	/**
	 * @covers Luki_Cache_memoryAdapter::Set
	 * @covers Luki_Cache_memoryAdapter::__construct
	 */
	public function testSet()
	{
		$this->assertTrue($this->object->Set($this->key, $this->value));
	}

	/**
	 * @covers Luki_Cache_memoryAdapter::Get
	 */
	public function testGet()
	{
		$this->assertFalse($this->object->Get('abc'));
		
		$this->assertEquals($this->object->Get($this->key), $this->value);
	}

	/**
	 * @covers Luki_Cache_memoryAdapter::Delete
	 */
	public function testDelete()
	{
		$this->assertFalse($this->object->Delete('abc'));
		
		$this->assertTrue($this->object->Delete($this->key));
	}

}
