<?php
require_once '/var/projects/Luki/Loader.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-23 at 13:28:03.
 */
class LoaderTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Luki_Loader
	 */
	protected $object;

	protected $sPath = '/var/projects/demo';
	
	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * Generated manualy.
	 *
	 * @covers Luki_Loader::Add
	 * @covers Luki_Loader::_Init
	 */
	public function testAdd()
	{
		Luki_Loader::Add($this->sPath);

		$aPath = Luki_Loader::getPath();
		
		$this->assertContains($this->sPath . '/', $aPath);
	}

	/**
	 * Generated manualy.
	 *
	 * @covers Luki_Loader::Add
	 * @covers Luki_Loader::_Init
	 */
	public function testAdd2()
	{
		Luki_Loader::Add($this->sPath . '/');

		$aPath = Luki_Loader::getPath();
		
		$this->assertContains($this->sPath . '/', $aPath);
	}

	/**
	 * @covers Luki_Loader::Autoload
	 * @todo   Implement testAutoload().
	 */
	public function testAutoload()
	{
		$oClass = new Luki_File;

		$this->assertEquals(is_a($oClass, 'Luki_File'), TRUE);
	}

	/**
	 * @covers Luki_Loader::getPath
	 * @todo   Implement testGetPath().
	 */
	public function testGetPath()
	{
		$aPath = Luki_Loader::getPath();
		
		$this->assertEquals(is_array($aPath), TRUE);
	}

	/**
	 * @covers Luki_Loader::getPath
	 * @todo   Implement testGetPath().
	 */
	public function testGetPath2()
	{
		$aPath = Luki_Loader::getPath();
		
		$this->assertEquals(empty($aPath), FALSE);
	}

	/**
	 * @covers Luki_Loader::isClass
	 * @covers Luki_Loader::_Init
	 * @todo   Implement testisClass().
	 */
	public function testisClass()
	{
		$sClassFileWithPath = Luki_Loader::isClass('Luki_Loader');
		
		$this->assertEquals(empty($sClassFileWithPath), FALSE);
	}

}
