<?php
require_once '../Loader.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-23 at 13:28:03.
 */
class Luki_LoaderTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Luki_Loader
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}

	/**
	 * Generated manualy.
	 *
	 * @covers Luki_Loader::Add
	 */
	public function testAdd()
	{
		$sPath = '/var/projects/demo';
		
		Luki_Loader::Add($sPath);

		$aPath = Luki_Loader::getPath();
			
		$this->assertContains($sPath, $aPath);
	}

	/**
	 * @covers Luki_Loader::Autoload
	 * @todo   Implement testAutoload().
	 */
	public function testAutoload()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Luki_Loader::getPath
	 * @todo   Implement testGetPath().
	 */
	public function testGetPath()
	{
		$aPath = Luki_Loader::getPath();
		
		$this->assertEquals(is_array($aPath), TRUE);
	}

	/**
	 * @covers Luki_Loader::getPath
	 * @todo   Implement testGetPath().
	 */
	public function testGetPath2()
	{
		$aPath = Luki_Loader::getPath();
		
		$this->assertEquals(empty($aPath), FALSE);
	}

}
