<?php
require_once '/var/projects/Luki/Storage.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-24 at 14:43:02.
 */
class Luki_StorageTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Luki_Storage
	 */
	protected $object;
	
	protected $key = 'alfa';
	
	protected $value = 'beta';

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
#		$this->object = new Luki_Storage;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}

	/**
	 * @covers Luki_Storage::Set
	 */
	public function testSet()
	{
		$this->assertFalse(Luki_Storage::Set(111, $this->value));
		$this->assertTrue(Luki_Storage::Set($this->key, $this->value));
	}

	/**
	 * @covers Luki_Storage::Get
	 */
	public function testGet()
	{
		Luki_Storage::Set($this->key, $this->value);
		$this->assertEquals(Luki_Storage::Get($this->key), $this->value);
		$this->assertNull(Luki_Storage::Get('abc'));
	}

	/**
	 * @covers Luki_Storage::isSaved
	 */
	public function testIsSaved()
	{
		$this->assertFalse(Luki_Storage::isSaved('abc'));
		$this->assertTrue(Luki_Storage::isSaved($this->key));
	}

}
